name: Het Industriegebouw
markdown: kramdown
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /journal/:year/:month/:day/:title/
port: '3000'
host: 'localhost'
# baseurl: 'http://broezer.github.io'
